### ISSUE TITLE
Copying connected worksurfaces will reset their size

### ISSUE THREAD

**Issue by tucaz** [Allsteel/awesome#244]
## Steps

1. Make a panel run with four 36"W panels
2. Place a primary worksurface on the first leftmost panel
3. Stretch it to 72"W
4. Single select the worksurface and hit "A" to copy it

The copy won't be 72"W but will be resized to 36"W instead. It works with FIKA.

### Ours

![resize](https://user-images.githubusercontent.com/111954/31641110-2f6b0aee-b2a8-11e7-85a9-3c92729dc1fe.gif)

### FIKA

![resize_fika](https://user-images.githubusercontent.com/111954/31641096-181a8770-b2a8-11e7-9ca9-7a7362a59c9e.gif)

**Comment by mbr4nt** [comment]
@tucaz maybe deactivate the auto-size on drag? only leave on insert animalesco?

**Comment by tucaz** [comment]
@mbr4nt makes sense!

**Comment by tucaz** [comment]
@mbr4nt the auto size is still happening after you copy it. I guess we just want that in the insert animation and nowhere else?

![drag2](https://user-images.githubusercontent.com/111954/31742770-5459885e-b41e-11e7-9e9d-3fb52247c901.gif)
