### ISSUE TITLE
Connect line is behaving strangely

### ISSUE THREAD

**Issue by bahiam** [Allsteel/awesome#273]
Connect line is limiting where to connect some objects in the line available space. For example, trying to connect a top trim on top of a stride panel only allows you to connect on the left side and center (see image below). This is also happening on another similar situation between worksurface and horizontal storage on stride.

![image](https://user-images.githubusercontent.com/16159431/32061803-44aa4f7c-ba38-11e7-80cd-48774e1a3db5.png)

**Comment by tucaz** [comment]
This is also happening with supports/credenzas under worksurfaces.
