### ISSUE TITLE
Add point support to preferred connections

### ISSUE THREAD

**Issue by tucaz** [Allsteel/awesome#355]
Tower to worksurface application has points instead of lines. Can we get them to show on preferred connector as well if that application is selected?

![image](https://user-images.githubusercontent.com/111954/33639783-a339a3b0-d9f2-11e7-8cd1-1111fab8dd61.png)

**Comment by mbr4nt** [comment]
@tucaz can I close this? It turns out it didn't need it.

**Comment by tucaz** [comment]
Sure!
